### ISSUE TITLE
求助：不支持模糊音

### ISSUE THREAD

**Issue by DDior** [psklf/my-config-file#1]
尝试了直接修改配置文件和打补丁两种方式，都无效，麻烦优化一下，谢谢

**Comment by psklf** [comment]
> 尝试了直接修改配置文件和打补丁两种方式，都无效，麻烦优化一下，谢谢

是指 `zh/z` 之类的模糊音吗？

这个我得稍稍研究一下。

**Comment by DDior** [comment]
> > 尝试了直接修改配置文件和打补丁两种方式，都无效，麻烦优化一下，谢谢
> 
> 是指 `zh/z` 之类的模糊音吗？
> 
> 这个我得稍稍研究一下。

我知道原因了，因为自然码2000的模糊音，和标准双拼的模糊音是不一样的，这个问题无解。
